### ISSUE TITLE
TypeError: Expected Ptr<cv::UMat> for argument 'src'

### ISSUE THREAD

**Issue by yosunpeng** [lzx1413/PytorchSSD#104]
Stop at epoch 10.
Here is the Traceback:
```
Traceback (most recent call last):                                               
    File "train_test.py", line 501, in <module>                                                                                                                             
        train()                                                                                                                                                                                
    File "train_test.py", line 312, in train                                                                                                                                                        
        top_k, thresh=0.01)                                                                                                                                                                         
    File "train_test.py", line 430, in test_net                                                                                                                                                        
         x = Variable(transform(img).unsqueeze(0), volatile=True)                                                                                                                 
   File "/home/yosunpeng/github/PytorchSSD-master/data/data_augment.py", line 251, in __call__                                                                                          
        self.resize), interpolation=interp_method).astype(np.float32)                                                                                                                                              
TypeError: Expected Ptr<cv::UMat> for argument 'src'              
```

**Comment by yosunpeng** [comment]
It is a pretty stupid problem. I didn't strictly follow the voc2007.sh. VOC2007-trainval and test should be tar -xvf to same files, and VOC2017 should be tar -xvf to aside tho VOC2007. Here is the file structure:
under the VOCdevkit/
![Screen Shot 2020-05-26 at 8 36 24 AM](https://user-images.githubusercontent.com/14315148/82849778-0fc27100-9f2c-11ea-88d7-0dc4f6e5f89f.png)
