### ISSUE TITLE
KeyError: 'unexpected key "0.weight" in state_dict'

### ISSUE THREAD

**Issue by charan223** [lzx1413/PytorchSSD#18]
Error while training RBF_mobile version

Loading base network...
Traceback (most recent call last):
  File "train_test.py", line 133, in <module>
    net.base.load_state_dict(base_weights)
  File "/home/xxxxx/anaconda2/envs/pyssd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
KeyError: 'unexpected key "0.weight" in state_dict'

**Comment by lzx1413** [comment]
The pre-train weight of the base model in RFB-mobile is not same as FSSD-mobile, you should use the corresponding pre-train weight.
