### ISSUE TITLE
有时候会遇到max_xy的invalid argument 1问题

### ISSUE THREAD

**Issue by dongfengxijian** [lzx1413/PytorchSSD#27]
Traceback (most recent call last):
  File "train_test.py", line 458, in <module>
    train()
  File "train_test.py", line 324, in train
    loss_l, loss_c = criterion(out, priors, targets)
  File "/home/phd/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/phd/PycharmProjects/PytorchSSD-master/layers/modules/multibox_loss.py", line 74, in forward
    match(self.threshold,truths,defaults,self.variance,labels,loc_t,conf_t,idx)
  File "/home/phd/PycharmProjects/PytorchSSD-master/utils/box_utils.py", line 108, in match
    point_form(priors)
  File "/home/phd/PycharmProjects/PytorchSSD-master/utils/box_utils.py", line 67, in jaccard
    inter = intersect(box_a, box_b)
  File "/home/phd/PycharmProjects/PytorchSSD-master/utils/box_utils.py", line 47, in intersect
    max_xy = torch.min(box_a[:, 2:].unsqueeze(1).expand(A, B, 2),
RuntimeError: invalid argument 1: the number of sizes provided must be greater or equal to the number of dimensions in the tensor at /opt/conda/conda-bld/pytorch_1518244507981/work/torch/lib/THC/generic/THCTensor.c:326

我是一块1080ti训练，pytorch0.3

**Comment by dongfengxijian** [comment]
@lzx1413 Thank you，I have finished it.
