### ISSUE TITLE
训练FSSD有问题

### ISSUE THREAD

**Issue by zyyhl** [lzx1413/PytorchSSD#35]
Epoch:10 || epochiter: 2048/2068|| Totel iter 20660 || L: 1.4363 C: 3.5825||Batch time: 0.2319 sec. ||LR: 0.00400000
Epoch:10 || epochiter: 2058/2068|| Totel iter 20670 || L: 1.5284 C: 3.6207||Batch time: 0.2024 sec. ||LR: 0.00400000
Traceback (most recent call last):
  File "train_test.py", line 456, in <module>
    train()
  File "train_test.py", line 280, in train
    top_k, thresh=0.01)
  File "train_test.py", line 395, in test_net
    out = net(x=x, test=True)  # forward pass
  File "/home/user/anaconda2/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda2/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 59, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/user/anaconda2/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 64, in replicate
    return replicate(module, device_ids)
  File "/home/user/anaconda2/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 12, in replicate
    param_copies = Broadcast(devices)(*params)
  File "/home/user/anaconda2/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 19, in forward
    outputs = comm.broadcast_coalesced(inputs, self.target_gpus)
  File "/home/user/anaconda2/envs/tensorflow-gpu/lib/python3.6/site-packages/torch/cuda/comm.py", line 48, in broadcast_coalesced
    if tensor.get_device() != devices[0]:
IndexError: tuple index out of range
请问作者遇到过这种问题吗，谢谢，我用的是python3.6和pytorch0.2

**Comment by lzx1413** [comment]
暂时没有出现过，这是多卡的问题吗

**Comment by zyyhl** [comment]
我变成单显卡还是会出现这个问题

**Comment by lzx1413** [comment]
最好把pytorch升级到0.3吧，我正在做向0.4的升级
