### ISSUE TITLE
训练COCO数据集时出错

### ISSUE THREAD

**Issue by dongfengxijian** [lzx1413/PytorchSSD#40]
> Traceback (most recent call last):
  File "train_test.py", line 501, in <module>
    train()
  File "train_test.py", line 308, in train
    collate_fn=detection_collate))
  File "/home/phd/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "/home/phd/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 234, in __init__
    w.start()
  File "/home/phd/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/phd/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/phd/anaconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/phd/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/home/phd/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
在VOC上训练时一切正常，但是在COCOval2017上训练时每第11epoch末尾处（例如epochiter: 7390/7392）就会出错，我想问问什么情况，有什么好办法？

**Comment by lzx1413** [comment]
内存不够了？

**Comment by lxtGH** [comment]
@dongfengxijian what is result of training COCO
