### ISSUE TITLE
Train tricks

### ISSUE THREAD

**Issue by lxtGH** [lzx1413/PytorchSSD#47]
Hi! Thanks for your code! Can you give **some advice on how to reproduce your result** in readme file.
For example RFBNet300, must train 300 epoch on voc to get your report point 80.5. Also, I found the **lr rate doesn't change** during the training, I got 66%map on voc 07 test after 90 epoch. I use the v.4.0 branch.

**Comment by lzx1413** [comment]
The lr will change at 150,200,250 epoches.

**Comment by lxtGH** [comment]
@lzx1413 Hi, I only got 78.3%MAP after 300 epochs training.

**Comment by lzx1413** [comment]
Which version of pytorch are you used.

**Comment by lxtGH** [comment]
pytorch 4.1 on branch 0.4, batch size 64, 4 GPU training.

**Comment by lzx1413** [comment]
I have not finished testing it. I will update the code in a few days.

**Comment by lxtGH** [comment]
@lzx1413 I don't why you set lr like that. I check the code and everything is OK

**Comment by lxtGH** [comment]
@lzx1413 according to this https://github.com/ruinmessi/RFBNet/issues/13
it maybe the version problem. I didn't try the 0.3.1 version.

**Comment by lxtGH** [comment]
@lzx1413 I got 79.7% on FSSD-300 which is beyond your benchmark. But RFB-net never reach that

**Comment by lzx1413** [comment]
The warn up epoch is 6 for rfb

**Comment by lxtGH** [comment]
Thanks! Finally got 80.3% RFB net

**Comment by lxtGH** [comment]
Can you share the COCO dataset training setting???

**Comment by lxtGH** [comment]
For example, How about the lr setting, batch size and how many epoch do we need to get the final score as the RFB paper

**Comment by dongfengxijian** [comment]
@lxtGH How do you ahcieve the 80.3%? Can you share the training setting?

**Comment by lxtGH** [comment]
@dongfengxijian  pytorch 4.1 on branch 0.4, batch size 64, 4 GPU training. Learning rate is as the default setting, warm up epoch is 6

**Comment by dongfengxijian** [comment]
@lxtGH Thank you!

**Comment by lxtGH** [comment]
Traceback (most recent call last):
  File "train_test.py", line 425, in <module>
    train()
  File "train_test.py", line 290, in train
    loss_l, loss_c = criterion(out, priors, targets)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lxt/PytorchSSD/layers/modules/multibox_loss.py", line 82, in forward
    pos_idx = pos.unsqueeze(pos.dim()).expand_as(loc_data)
RuntimeError: The expanded size of the tensor (32752) must match the existing size (32756) at non-singleton dimension 1
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f00b39af668>>
Traceback (most recent call last):
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/lxt/anaconda3/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Have you met this problem when using 512 train size

**Comment by WangTianYuan** [comment]
@lxtGH Have you solved this problem? I have no idea how to change the code

**Comment by sagittahjz** [comment]
@lxtGH  @WangTianYuan 
You should attach [128, 'S', 256] to the end of extras['512'] in SSD_vgg.py

**Comment by lxtGH** [comment]
Yes, it miss the last bolocks
